### ISSUE TITLE
Add default browser selection for opening links & video calls

### ISSUE THREAD

**Issue by Ariandr** [pakerwreah/Calendr#255] opened 2024-09-24 20:04 UTC
Hi!
My use case is that I moved my working calendar to Apple Calendar to use with Calendr app. There I have a lot of video calls with links.

But my default browser is not my working browser, so wherever I click the events to open the meetings (Google Meets mostly), it launches them in the wrong browser and I have to copy the link and open it in another browser.

1) My idea is that it would be really great to set the default browser for opening links in the Calendr Settings.

2) Or, provide the option to open it in a specific browser (after right clicking near `Join`), like in the Mail app:
![image](https://github.com/user-attachments/assets/eb87f968-8bcf-4d32-b02c-a4820f2b3388)

3) Or, have the option to `Copy link` here, so that I can insert it where I need to without launching the meeting in the wrong browser first. I know the link is available in the event details, but I have a long description there and it's not convenient to copy the link from the details.
![image](https://github.com/user-attachments/assets/c2bc6d6b-6186-444d-9d44-5e24579b7d1a)

What do you think about these ideas?

**Comment by Ariandr** [comment] 2024-09-24 20:38
This is how we can detect what browsers are installed.

```
import Cocoa

func getInstalledBrowsers() -> [String] {
    let browserBundleIDs = [
        // Popular browsers
        "com.apple.Safari",               // Safari
        "com.google.Chrome",              // Google Chrome
        "org.mozilla.firefox",            // Mozilla Firefox
        "com.microsoft.edgemac",          // Microsoft Edge
        "com.operasoftware.Opera",        // Opera
        "com.brave.Browser",              // Brave
        "com.vivaldi.Vivaldi",            // Vivaldi

        // Alternative browsers
        "com.maxthon.mac.Maxthon",        // Maxthon
        "com.torproject.torbrowser",      // Tor Browser
        "com.flock.Flock",                // Flock
        "com.seamonkey-project.SeaMonkey",// SeaMonkey
        "org.waterfoxproject.waterfox",   // Waterfox
        "com.qutebrowser.qutebrowser",    // qutebrowser

        // Developer-focused browsers
        "com.coastbyopera.Coast",         // Opera Coast
        "org.webkit.WebKit",              // WebKit

        // Other niche or privacy-focused browsers
        "com.sleipnir.Sleipnir",          // Sleipnir
        "com.epicbrowser.epic",           // Epic Privacy Browser
        "org.isc.roccat",                 // Roccat Browser
        "org.ghostbrowser.GhostBrowser",  // Ghost Browser
        "com.avast.osx.securebrowser",    // Avast Secure Browser
        "com.cliqz.browser",              // Cliqz
        "com.uc.browser",                 // UC Browser
    ]
    
    var installedBrowsers: [String] = []
    
    let workspace = NSWorkspace.shared
    for bundleID in browserBundleIDs {
        if let appURL = workspace.urlForApplication(withBundleIdentifier: bundleID) {
            installedBrowsers.append("\(bundleID) at: \(appURL.path)")
        }
    }
    
    return installedBrowsers
}

// Usage example:
let browsers = getInstalledBrowsers()
if browsers.isEmpty {
    print("No browsers found.")
} else {
    for browser in browsers {
        print("Found browser: \(browser)")
    }
}
```

And that's how we can launch a URL inside the selected one.
```
import Cocoa

func openURLInBrowser(urlString: String, browserBundleID: String) {
    guard let url = URL(string: urlString) else {
        print("Invalid URL string.")
        return
    }

    let workspace = NSWorkspace.shared
    if let browserURL = workspace.urlForApplication(withBundleIdentifier: browserBundleID) {
        do {
            try workspace.open([url], withApplicationAt: browserURL, options: [], configuration: [:])
            print("Opened \(urlString) in \(browserBundleID).")
        } catch {
            print("Failed to open \(urlString) in \(browserBundleID): \(error).")
        }
    } else {
        print("Browser with bundle ID \(browserBundleID) is not installed.")
    }
}

// Usage example:
let browserBundleID = "com.google.Chrome"  // Change to the browser's bundle ID you want
let urlString = "https://www.example.com"

openURLInBrowser(urlString: urlString, browserBundleID: browserBundleID)
```

**Comment by pakerwreah** [comment] 2024-09-24 20:46
I have a working browser as well. I use an app called [Finicky](https://github.com/johnste/finicky) as my "default browser" and I configure which browser should open the URL.

```js
module.exports = {
  defaultBrowser: "Safari",
  handlers: [
    {
      match: [
        "notion.*/*",
        "*.notion.*/*",
        "linear.app/*",
        "*.linear.app/*",
        "play.google.com/*",
        "developers.facebook.com/*",
        '*.figma.com/*',
        'console.cloud.google.com/*',
        "*.aws.amazon.com/*",
      ],
      /*browser: {
        name: "Google Chrome",
        profile: "Profile 1"
      }*/
      browser: ({ urlString }) => ({
        name: "Firefox",
        args: ["-P", "Profile 1", `${urlString}`]
      })
    }
  ]
}
```

That has the advantage of being system-wise, so if I click a link on Slack, for example, it also routes to my work browser.

**Comment by Ariandr** [comment] 2024-09-24 20:52
@pakerwreah 
Cool, thanks for the advice.

But probably would be nice to have it in the Calendr app in some form too, since most users don't have such helper apps.

**Comment by Ariandr** [comment] 2024-09-24 21:14
I think when I have time I'll work on it and come up with a PR.

**Comment by pakerwreah** [comment] 2024-09-24 21:19
The problem is that a context menu will not be helpful, as it will become extremely frustrating and repetitive.
Defining a default browser is also not enough, as you can have mixed work and personal calendars.
So we would need to have a default browser per calendar, which is a bit too much.

That said, it should be pretty simple, actually. You don't have to map every browser.
https://ericmaciel.me/posts/how-to-get-the-list-of-installed-browsers-on-macos

Feel free to implement this, but I'm probably not merge it, as it's beyond the scope of Calendr.
Unless I find a simple and non-intrusive way of doing it.

**Comment by pakerwreah** [comment] 2024-09-25 03:06
It's done 😂
could you please try out this version? 
[Calendr.zip](https://github.com/user-attachments/files/17123978/Calendr.zip)

<img height=200 src='https://github.com/user-attachments/assets/376b79f3-cdb2-41aa-82ee-85fe848e506b' />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img height =200 src='https://github.com/user-attachments/assets/cdb4c281-17df-47ab-9e12-5de8b4ea4b65' />
<br><br>

I will add more stuff to it before releasing, so remember to download and reinstall after the official release comes out.

**Comment by Ariandr** [comment] 2024-09-25 06:51
@pakerwreah 
You rock🔥🔥🔥
Thank you a lot, I will try now.

**Comment by Ariandr** [comment] 2024-09-25 07:06
@pakerwreah 
Cannot find where it's placed.
In event details it's not available for me it seems.
![image](https://github.com/user-attachments/assets/6713d820-4b41-40af-988d-0e1b77cca20d)

**Comment by Ariandr** [comment] 2024-09-25 07:15
@pakerwreah 
I found, it's available only in events with usual links, but not video calls🙂

Found several issues:
1) The icon disappears from here sometimes, and sometimes appears.
![image](https://github.com/user-attachments/assets/22836246-ce57-480a-b383-7b3aa47d8fa1)

2) While the correct browser with the link is opened when clicking here, the link itself is not opened.
![image](https://github.com/user-attachments/assets/d00a87ea-31a1-4c3d-a953-1cbc4cdfed7a)

**Comment by Ariandr** [comment] 2024-09-25 07:27
Also, just a question to consider.
Maybe it would be possible to move it to Calendars preferences? Or do you think too clumsy?

I also think if it's a default browser, after selection the browser option it can be without the icon, like in the 1. bug I showed you. And if it's not default, then it will be with the icon. So that by default it's not intrusive.

![image](https://github.com/user-attachments/assets/067d887e-8b45-4daa-bde4-59f72cee027c)

**Comment by pakerwreah** [comment] 2024-09-25 08:03
Yeah, I wrongly assumed that I was only showing native apps as video calls. I forgot about google meet/hangouts.

About moving it to preferences, it would have to be per calendar, that's why I don't want to do it there.

**Comment by Ariandr** [comment] 2024-09-25 08:30
@pakerwreah 
Okay, that makes sense, regarding the preferences.

Definitely it would be enough to just have it near the links/video calls.

**Comment by pakerwreah** [comment] 2024-09-25 13:16
I completely forgot to open the link 🤣

- Icon is hidden when selecting the default browser
- Show browser selector for any regular http urls
- Links are now actually opening, not just the browser

👉🏻  [Calendr.zip](https://github.com/user-attachments/files/17131477/Calendr.zip)

**Comment by Ariandr** [comment] 2024-09-25 13:24
@pakerwreah 
Great, thank you. I will test.

**Comment by Ariandr** [comment] 2024-09-25 13:37
@pakerwreah 
It works, but after selecting another browser it sometimes treats a non-default browser as default. In my case Opera is default, but it shows Chrome as default. Not a big deal though.
![image](https://github.com/user-attachments/assets/efe0a505-9d58-4fac-8501-9005400efb22)

**Comment by pakerwreah** [comment] 2024-09-25 13:58
Hum 🤔 it should always show the default first. Than can cause problems, let me gave a look.

**Comment by pakerwreah** [comment] 2024-09-25 15:37
yeah, I'm just dumb and don't know how to sort multiple keys 😆

we're almost there... [Calendr.zip](https://github.com/user-attachments/files/17134194/Calendr.zip)

**Comment by Ariandr** [comment] 2024-09-25 15:50
@pakerwreah 
Now seems working well🙂

**Closed** 2024-10-07 21:08 UTC
Labels: feature
